version: "3.9"

services:
  db:
    image:  postgres:12.11-alpine
    # ports:
    #   - "5438:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT='5432'
      - ALLOW_IP_RANGE=0.0.0.0/0
  web:
    build:
      context: ./
      dockerfile: Dockerfile 
    command: python manage.py runserver 0.0.0.0:8014
    volumes:
      - .:/code
    ports:
      - "8014:8014"
    depends_on:
      - db